// src/pages/ProductionSections/SpiralSection/SpiralView.jsx
import React, { useState, useEffect } from 'react';
import { 
  FiArrowLeft, FiPackage, FiEdit, FiPrinter, FiDownload,
  FiTool, FiBox, FiHash, FiUser, FiCalendar, 
  FiTarget, FiTrendingUp, FiBarChart2, FiGrid,
  FiCheck, FiAlertCircle, FiDollarSign, FiClock,
  FiTag, FiLayers, FiSliders, FiArchive
} from 'react-icons/fi';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '../../../supabaseClient';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const SpiralView = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  
  const [record, setRecord] = useState(null);
  const [loading, setLoading] = useState(true);
  const [targetDetails, setTargetDetails] = useState(null);
  const [relatedItems, setRelatedItems] = useState([]);

  useEffect(() => {
    fetchRecordDetails();
  }, [id]);

  const fetchRecordDetails = async () => {
    try {
      setLoading(true);
      
      // 1. ریکارڈ کی مکمل تفصیلات
      const { data: recordData, error: recordError } = await supabase
        .from('spiralsection')
        .select('*')
        .eq('id', id)
        .single();

      if (recordError) {
        console.error('Error fetching record:', recordError);
        alert('Record not found!');
        navigate('/production-sections/spiral');
        return;
      }

      setRecord(recordData);

      // 2. متعلقہ ٹارگٹ کی تفصیلات
      const { data: targetData } = await supabase
        .from('targets')
        .select('*')
        .eq('machine_id', recordData.machine_id)
        .eq('shift_code', recordData.shift || recordData.shift_code)
        .eq('section', 'Spiral')
        .single();

      setTargetDetails(targetData);

      // 3. اسی آئٹم کی دوسری پیداواریں
      const { data: relatedData } = await supabase
        .from('spiralsection')
        .select('*')
        .eq('item_code', recordData.item_code)
        .neq('id', id)
        .order('created_at', { ascending: false })
        .limit(5);

      setRelatedItems(relatedData || []);

    } catch (error) {
      console.error('Error fetching details:', error);
      alert('Error loading record details');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text('Spiral Section Production Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Report ID: ${record?.id} | Date: ${new Date(record?.created_at).toLocaleDateString()}`, 105, 30, { align: 'center' });
    
    // Basic Information
    doc.setFontSize(14);
    doc.setTextColor(16, 185, 129);
    doc.text('Basic Information', 20, 45);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Machine: ${record?.machine_id} (${record?.machine_no})`, 20, 55);
    doc.text(`Shift: ${record?.shift_name || record?.shift}`, 20, 60);
    doc.text(`Operator: ${record?.operator_name}`, 20, 65);
    doc.text(`Date: ${new Date(record?.created_at).toLocaleString()}`, 20, 70);
    
    // Production Details
    doc.setFontSize(14);
    doc.setTextColor(59, 130, 246);
    doc.text('Production Details', 20, 85);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Item: ${record?.item_name} (${record?.item_code})`, 20, 95);
    doc.text(`Production Quantity: ${record?.production_quantity} ${record?.unit || 'Meter'}`, 20, 100);
    doc.text(`Per Meter Weight: ${record?.per_meter_wt} KG`, 20, 105);
    doc.text(`Total Weight: ${record?.weight} KG`, 20, 110);
    
    // Efficiency & Target
    doc.setFontSize(14);
    doc.setTextColor(245, 158, 11);
    doc.text('Performance Metrics', 20, 125);
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Efficiency: ${record?.efficiency}%`, 20, 135);
    doc.text(`Target: ${targetDetails?.target_qty || 'N/A'} ${targetDetails?.uom || 'Meter'}`, 20, 140);
    doc.text(`Status: ${record?.efficiency > 100 ? 'Over Target' : record?.efficiency >= 90 ? 'Excellent' : record?.efficiency >= 80 ? 'Good' : 'Below Target'}`, 20, 145);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Pakistan Wire Industries ERP System', 105, 280, { align: 'center' });
    doc.text(new Date().toLocaleString(), 105, 285, { align: 'center' });
    
    doc.save(`Spiral_Record_${record?.id}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handleEdit = () => {
    navigate(`/production-sections/spiral/edit/${id}`);
  };

  const getEfficiencyColor = (efficiency) => {
    if (efficiency > 100) return '#ef4444';
    if (efficiency >= 90) return '#10b981';
    if (efficiency >= 80) return '#f59e0b';
    return '#ef4444';
  };

  const getEfficiencyStatus = (efficiency) => {
    if (efficiency > 100) return 'Over Target';
    if (efficiency >= 90) return 'Excellent';
    if (efficiency >= 80) return 'Good';
    return 'Below Target';
  };

  if (loading) {
    return (
      <div style={{ 
        padding: '50px', 
        textAlign: 'center', 
        color: '#64748b' 
      }}>
        <div style={{ 
          width: '40px', 
          height: '40px', 
          border: '3px solid #e2e8f0',
          borderTopColor: '#10b981',
          borderRadius: '50%',
          animation: 'spin 1s linear infinite',
          margin: '0 auto 20px'
        }} />
        <p>Loading record details...</p>
      </div>
    );
  }

  if (!record) {
    return (
      <div style={{ padding: '50px', textAlign: 'center' }}>
        <div style={{ fontSize: '48px', color: '#ef4444', marginBottom: '20px' }}>⚠️</div>
        <h3 style={{ color: '#1e293b' }}>Record Not Found</h3>
        <p style={{ color: '#64748b', marginBottom: '30px' }}>The requested record could not be found.</p>
        <button
          onClick={() => navigate('/production-sections/spiral')}
          style={{
            background: '#3b82f6',
            color: 'white',
            border: 'none',
            padding: '12px 24px',
            borderRadius: '8px',
            cursor: 'pointer',
            fontWeight: '600'
          }}
        >
          Back to Spiral Section
        </button>
      </div>
    );
  }

  return (
    <div style={{ padding: '20px', maxWidth: '1200px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '30px',
        flexWrap: 'wrap',
        gap: '20px'
      }}>
        <div>
          <button
            onClick={() => navigate('/production-sections/spiral')}
            style={{
              background: 'transparent',
              border: 'none',
              color: '#64748b',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              fontSize: '14px',
              marginBottom: '10px',
              padding: '8px 16px',
              borderRadius: '8px',
              transition: 'all 0.2s ease'
            }}
          >
            <FiArrowLeft /> Back to Spiral Section
          </button>
          <h1 style={{
            margin: '0',
            fontSize: '32px',
            color: '#1e293b',
            display: 'flex',
            alignItems: 'center',
            gap: '15px'
          }}>
            <div style={{
              width: '60px',
              height: '60px',
              background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
              borderRadius: '15px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiPackage size={28} />
            </div>
            Spiral Section Record Details
          </h1>
          <p style={{ 
            margin: '10px 0 0 75px', 
            color: '#64748b',
            fontSize: '16px'
          }}>
            Record ID: {record.id} | Created: {new Date(record.created_at).toLocaleString()}
          </p>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', gap: '15px', flexWrap: 'wrap' }}>
          <button
            onClick={handleEdit}
            style={{
              background: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
              border: 'none',
              padding: '12px 24px',
              borderRadius: '10px',
              color: 'white',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              fontWeight: '600'
            }}
          >
            <FiEdit /> Edit Record
          </button>
          
          <button
            onClick={handlePrint}
            style={{
              background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
              border: 'none',
              padding: '12px 24px',
              borderRadius: '10px',
              color: 'white',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              fontWeight: '600'
            }}
          >
            <FiPrinter /> Print
          </button>
          
          <button
            onClick={handleDownloadPDF}
            style={{
              background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
              border: 'none',
              padding: '12px 24px',
              borderRadius: '10px',
              color: 'white',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              fontWeight: '600'
            }}
          >
            <FiDownload /> Download PDF
          </button>
        </div>
      </div>

      {/* Main Content Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))',
        gap: '25px',
        marginBottom: '30px'
      }}>
        {/* Card 1: Basic Information */}
        <div style={{
          background: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '25px',
          border: '1px solid #e5e7eb'
        }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px', 
            marginBottom: '20px' 
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiHash size={20} />
            </div>
            <h3 style={{ margin: '0', color: '#1e293b', fontSize: '20px' }}>
              Basic Information
            </h3>
          </div>

          <div style={{ display: 'grid', gap: '15px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Section</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.section_name}</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Machine ID</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.machine_id}</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Machine No</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.machine_no}</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Shift</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.shift_name || record.shift}</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <div style={{ color: '#64748b' }}>Operator</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.operator_name}</div>
            </div>
          </div>
        </div>

        {/* Card 2: Item Details */}
        <div style={{
          background: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '25px',
          border: '1px solid #e5e7eb'
        }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px', 
            marginBottom: '20px' 
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiBox size={20} />
            </div>
            <h3 style={{ margin: '0', color: '#1e293b', fontSize: '20px' }}>
              Item Details
            </h3>
          </div>

          <div style={{ display: 'grid', gap: '15px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Item Code</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.item_code}</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Item Name</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.item_name}</div>
            </div>
            
            {record.finishedproductname && (
              <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
                <div style={{ color: '#64748b' }}>Finished Product</div>
                <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.finishedproductname}</div>
              </div>
            )}
            
            {record.raw_material_flatsize && (
              <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
                <div style={{ color: '#64748b' }}>Raw Material Size</div>
                <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.raw_material_flatsize}</div>
              </div>
            )}
            
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <div style={{ color: '#64748b' }}>Material Type</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.material_type || 'N/A'}</div>
            </div>
          </div>
        </div>

        {/* Card 3: Production Details */}
        <div style={{
          background: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '25px',
          border: '1px solid #e5e7eb'
        }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px', 
            marginBottom: '20px' 
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiTool size={20} />
            </div>
            <h3 style={{ margin: '0', color: '#1e293b', fontSize: '20px' }}>
              Production Details
            </h3>
          </div>

          <div style={{ display: 'grid', gap: '15px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Production Quantity</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>
                {record.production_quantity} {record.unit || 'Meter'}
              </div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Per Meter Weight</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.per_meter_wt} KG</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Total Weight</div>
              <div style={{ fontWeight: '600', color: '#10b981', fontSize: '18px' }}>
                {record.weight} KG
              </div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Created Date</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>
                {new Date(record.created_at).toLocaleString()}
              </div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <div style={{ color: '#64748b' }}>Last Updated</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>
                {new Date(record.updated_at || record.created_at).toLocaleString()}
              </div>
            </div>
          </div>
        </div>

        {/* Card 4: Performance Metrics */}
        <div style={{
          background: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '25px',
          border: '1px solid #e5e7eb'
        }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px', 
            marginBottom: '20px' 
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              background: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiTarget size={20} />
            </div>
            <h3 style={{ margin: '0', color: '#1e293b', fontSize: '20px' }}>
              Performance Metrics
            </h3>
          </div>

          <div style={{ display: 'grid', gap: '15px' }}>
            <div style={{ 
              display: 'flex', 
              justifyContent: 'space-between', 
              alignItems: 'center',
              paddingBottom: '10px', 
              borderBottom: '1px solid #f1f5f9' 
            }}>
              <div style={{ color: '#64748b' }}>Efficiency</div>
              <div style={{ 
                fontWeight: '700', 
                fontSize: '24px',
                color: getEfficiencyColor(record.efficiency)
              }}>
                {record.efficiency}%
              </div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Status</div>
              <div style={{ 
                fontWeight: '600', 
                color: getEfficiencyColor(record.efficiency),
                background: `${getEfficiencyColor(record.efficiency)}20`,
                padding: '4px 12px',
                borderRadius: '20px'
              }}>
                {getEfficiencyStatus(record.efficiency)}
              </div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>Shift Target</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>
                {targetDetails ? `${targetDetails.target_qty} ${targetDetails.uom}` : 'Not Available'}
              </div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ color: '#64748b' }}>User</div>
              <div style={{ fontWeight: '600', color: '#1e293b' }}>{record.users_name || 'System'}</div>
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <div style={{ color: '#64748b' }}>Record ID</div>
              <div style={{ fontWeight: '600', color: '#64748b', fontFamily: 'monospace' }}>
                #{record.id}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Remarks Section */}
      {record.remarks && (
        <div style={{
          background: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '25px',
          marginBottom: '30px',
          border: '1px solid #e5e7eb'
        }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px', 
            marginBottom: '20px' 
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              background: 'linear-gradient(135deg, #64748b 0%, #475569 100%)',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiArchive size={20} />
            </div>
            <h3 style={{ margin: '0', color: '#1e293b', fontSize: '20px' }}>
              Remarks
            </h3>
          </div>
          
          <div style={{
            background: '#f8fafc',
            padding: '20px',
            borderRadius: '8px',
            borderLeft: '4px solid #8b5cf6',
            fontStyle: 'italic',
            color: '#475569'
          }}>
            {record.remarks}
          </div>
        </div>
      )}

      {/* Related Records */}
      {relatedItems.length > 0 && (
        <div style={{
          background: 'white',
          borderRadius: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
          padding: '25px',
          marginBottom: '30px',
          border: '1px solid #e5e7eb'
        }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '15px', 
            marginBottom: '20px' 
          }}>
            <div style={{
              width: '40px',
              height: '40px',
              background: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white'
            }}>
              <FiLayers size={20} />
            </div>
            <h3 style={{ margin: '0', color: '#1e293b', fontSize: '20px' }}>
              Related Production Records
            </h3>
          </div>
          
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: '#f8fafc' }}>
                  <th style={{ padding: '12px', textAlign: 'left', color: '#64748b', fontWeight: '600' }}>Date</th>
                  <th style={{ padding: '12px', textAlign: 'left', color: '#64748b', fontWeight: '600' }}>Machine</th>
                  <th style={{ padding: '12px', textAlign: 'left', color: '#64748b', fontWeight: '600' }}>Quantity</th>
                  <th style={{ padding: '12px', textAlign: 'left', color: '#64748b', fontWeight: '600' }}>Weight</th>
                  <th style={{ padding: '12px', textAlign: 'left', color: '#64748b', fontWeight: '600' }}>Efficiency</th>
                  <th style={{ padding: '12px', textAlign: 'left', color: '#64748b', fontWeight: '600' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {relatedItems.map((item) => (
                  <tr key={item.id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                    <td style={{ padding: '12px', color: '#64748b' }}>
                      {new Date(item.created_at).toLocaleDateString()}
                    </td>
                    <td style={{ padding: '12px', fontWeight: '600' }}>{item.machine_id}</td>
                    <td style={{ padding: '12px' }}>
                      {item.production_quantity} {item.unit || 'Meter'}
                    </td>
                    <td style={{ padding: '12px', color: '#10b981', fontWeight: '600' }}>
                      {item.weight} KG
                    </td>
                    <td style={{ padding: '12px' }}>
                      <div style={{ 
                        display: 'inline-block',
                        fontWeight: '600',
                        color: getEfficiencyColor(item.efficiency),
                        background: `${getEfficiencyColor(item.efficiency)}20`,
                        padding: '4px 12px',
                        borderRadius: '20px'
                      }}>
                        {item.efficiency}%
                      </div>
                    </td>
                    <td style={{ padding: '12px' }}>
                      <button
                        onClick={() => navigate(`/production-sections/spiral/view/${item.id}`)}
                        style={{
                          background: 'transparent',
                          border: '1px solid #3b82f6',
                          color: '#3b82f6',
                          padding: '6px 12px',
                          borderRadius: '6px',
                          cursor: 'pointer',
                          fontSize: '13px'
                        }}
                      >
                        View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          
          #printable-area, #printable-area * {
            visibility: visible;
          }
          
          #printable-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            padding: 20px;
          }
          
          button {
            display: none !important;
          }
        }
        
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default SpiralView;